### ISSUE TITLE
Connections MVP Checklist

### ISSUE THREAD

**Issue by hiendbui** [hiendbui/OptIn#11]
# Connections
## Functionality
- [x] Smooth, bug free navigation
- [ ] Able to view  connections and suggestions for connections ('people you may know') on network page
- [x] Can connect with suggestions and disconnect on network page
- [x] Can connect with any user or disconnect on their profile page
- [ ] Connection count for each profile is updated at each connect/disconnect
## Style
- [x] The profile previews on the network page look like those of the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] Remove Redux logger and all console.log()'s from production

**Comment by mkayys** [comment]
![Screen Shot 2020-12-17 at 6 01 38 PM](https://user-images.githubusercontent.com/48598856/102565267-fc2a5380-4091-11eb-9442-b40c76d5f6c1.png)
- have 3 connections, but only see 1?
![Screen Shot 2020-12-17 at 6 02 01 PM](https://user-images.githubusercontent.com/48598856/102565284-03516180-4092-11eb-8213-a91a0c7345a7.png)
- ^ also is it a design choice to leave the dropdown unless I click my profile icon again to exit?
