### ISSUE TITLE
User Auth MVP Checklist

### ISSUE THREAD

**Issue by hiendbui** [hiendbui/OptIn#3]
# User Auth
## Functionality
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by mkayys** [comment]
- `Join Now` and `Sign In` buttons jiggle on hover
- no errors displayed when clicking `Sign in` button without filling out form and error in console
- image broken for newly signed up user
![Screen Shot 2020-12-10 at 5 57 50 PM](https://user-images.githubusercontent.com/48598856/101851867-400cde00-3b11-11eb-86f8-6fcfb95127ff.png)
- can't sign in
- log out button needs styling
- remove blue border when clicking on an element (default for links I believe)

**Comment by hiendbui** [comment]
Hi Michelle, thanks for the feedback! Looks the the sign in problems only came after a recent push and I didn't realize my changes affected it. Thank you esp for the suggestion to remove the blue border for buttons! Outside of the logout button, everything is addressed! That logout button is only temporarily there for testing so that I don't have to dispatch my logout action through the console. Later I'll implement a logout link in the drop down menu from the 'me' button.

**Comment by mkayys** [comment]
I see, technically Logout styling is a part of the User Auth MVP but sounds good! It's looking much better and the Sign In seems to work now.
