### ISSUE TITLE
Profile MVP Checklist

### ISSUE THREAD

**Issue by hiendbui** [hiendbui/OptIn#8]
# Profile
## Functionality
- [x] Has working demo profile
- [x] Smooth, bug free navigation
- [x] Able to create/update main parts of profile (name, headline, location, description, profile pic)
- [ ] CRUD operations work for experiences
- [ ] CRUD operations work for educations
- [ ] CRUD operations work for achievements
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] Remove Redux logger and all console.log()'s from production

**Comment by mkayys** [comment]
- looks like no errors are rendered for the education/experience/achievement forms
